server:
  port: 8601
spring:
  rabbitmq:
    host: rabbitmq-server
    port: 5672
    username: mldnjava
    password: hello
    virtual-host: /
  datasource:
    url: jdbc:mysql://localhost:3306/zipkin
    username: root
    password: mysqladmin
    driver-class-name: org.gjt.mm.mysql.Driver
    initialize: true
    continue-on-error: true
  application:
    name: microcloud-zipkin-server

zipkin:
  storage:  # 设置zipkin收集的信息通过mysql进行存储
    type: mysql